expname: hare2
objpath: ./data/animal/hare2.obj
optimizer: MomentumBrake
lr: 0.001
savepath: ./results/animal
max_collisions: 16
energy: signed_TPE_verts
lap: cotan
constraints:
  - curvature
  - area
  - volume
timing: false
